version: '3.9'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: medregia
    ports:
      - "3307:3306"  # Mapping host port 3307 to container port 3306
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/medregia
    ports:
      - "8000:8000"
    depends_on:
      - db
